# server_url points to the HY452 server
server_url: https://qtbkf4jg4c.execute-api.eu-central-1.amazonaws.com/beta

# custom_server_url points to your server (or your friend's server)
custom_server_url: https://qtbkf4jg4c.execute-api.eu-central-1.amazonaws.com/beta


# For your convenience, you can add your credentials here
# By doing so, you will not have to enter them every time you run the game
# Default values: local Player
player_name: "Player"

email: "player@csd.uoc.gr"

password: "password"